CREATE TABLE jogador
(
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    username     VARCHAR(255),
    password     VARCHAR(255),
    avaliacao DOUBLE PRECISION                     NOT NULL,
    role                VARCHAR(255),
    active              BOOLEAN DEFAULT TRUE NOT NULL,
    account_expired     BOOLEAN DEFAULT FALSE NOT NULL,
    account_locked      BOOLEAN DEFAULT FALSE NOT NULL,
    credentials_expired BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT pk_jogador PRIMARY KEY (id)
);

ALTER TABLE jogador
    ADD CONSTRAINT uc_jogador_username UNIQUE (username);

CREATE TABLE racha
(
    id                INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID,
    localizacao       VARCHAR(255),
    clima             VARCHAR(255),
    data              VARCHAR(255),
    quantidade_maxima INT                                  NOT NULL,
    quantidade_atual  INT                                  NOT NULL,
    disponivel        BOOLEAN                              NOT NULL,
    esporte           VARCHAR(255),
    avaliacao_minima  INT                                  NOT NULL,
    duracao           VARCHAR(255),
    dono_da_bola      VARCHAR(255),
    prioridade        VARCHAR(255),
    CONSTRAINT pk_racha PRIMARY KEY (id)
);

CREATE TABLE racha_jogador
(
    jogador_id INT NOT NULL,
    racha_id   INT NOT NULL,
    CONSTRAINT pk_racha_jogador PRIMARY KEY (jogador_id, racha_id)
);

ALTER TABLE racha_jogador
    ADD CONSTRAINT fk_racjog_on_jogador FOREIGN KEY (jogador_id) REFERENCES jogador (id);

ALTER TABLE racha_jogador
    ADD CONSTRAINT fk_racjog_on_racha FOREIGN KEY (racha_id) REFERENCES racha (id);

CREATE TABLE partida
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero   INT                                  NOT NULL,
    timea    VARCHAR(255),
    timeb    VARCHAR(255),
    duracao  VARCHAR(255),
    placar   VARCHAR(255),
    racha_id INT,
    CONSTRAINT pk_partida PRIMARY KEY (id)
);

ALTER TABLE partida
    ADD CONSTRAINT FK_PARTIDA_ON_RACHA FOREIGN KEY (racha_id) REFERENCES racha (id);